### ISSUE TITLE
[Chore] Update README with project setup details

### ISSUE THREAD

**Issue by olivierobert** [thanakij/serp-web#2]
## Issue

While there are `env.sample` files and you provided instructions by email on how to set up each application, it would be best to enhance the current README files with the setup steps and dependency requirements (e.g., Node version). 

> **Note**
> The database used on the API seems also used on the Next.JS client application so it would also be best to provide the orchestration steps, i.e., the API applications must be run before. In addition, you might be interested in using a Makefile to simplify the setup steps 💡

**Comment by thanakij** [comment]
There is also [one](https://github.com/thanakij/serp-api/pull/3) for serp-api repo.
